version: "3"

services:
  db:
    image: "postgres"
    container_name: "motorcycle_container"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "54320:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
